### ISSUE TITLE
Enter transfer credit (2)

### ISSUE THREAD

**Issue by skiadas** [sdp-resources/MajorPlanner#26]
Needs points and refinement.

- Should it instead be named "mark requirement as satisfied"?
- Should this be done by "adjusting" the requirement, or by allowing some list of "credit" courses in the schedule?

**Comment by CelesteHackmann** [comment]
I like "mark requirement as satisfied"
I'm assuming this refers to when the student completes the class.

**Comment by Hayesb20** [comment]
2

**Comment by dantg21** [comment]
2

**Comment by smithma21** [comment]
2

**Comment by skiadas** [comment]
@CelesteHackmann Actually this refers to transfer credit or AP credit. For example you may have taken the CS AP exam and thus have credit for CS220. So we need to mark that you don't  need that requirement, but the course doesn't go into your schedule. One way to approach it would be to allow, in addition with the normal term slots in a schedule, an arbitrary list of "previously earned credits" items.

**Comment by marsht21** [comment]
4

**Comment by CelesteHackmann** [comment]
2
