### ISSUE TITLE
Compare schedule to its requirement(s) (8) 

### ISSUE THREAD

**Issue by skiadas** [sdp-resources/MajorPlanner#4]
We need to split this story into smaller stories, e.g.:

- Compare schedule to single program requirement
- Compare schedule to multiple program requirements without double-dipping
- Compare schedule to multiple program requirements with arbitrary double-dipping
- Compare schedule to multiple program requirements with rule-based double-dipping

**Comment by Hayesb20** [comment]
5

**Comment by skiadas** [comment]
Splitting this up to #31, #32 and #33
